cursor #efdfe1
cursor_text_color #d6c2c5

foreground            #efdfe1
background            #191113
selection_foreground  #422930
selection_background  #e3bdc5
url_color             #ffb1c5

color0   #191113
color1   #ff7277
color2   #9eff7f
color3   #ffe272
color4   #f299b0
color5   #763344
color6   #ffb1c5
color7   #ffeff3
color8   #a5999c
color9   #ff9fa2
color10  #bbffa5
color11  #ffeca5
color12  #ffbccd
color13  #ffc8d6
color14  #ffdbe4
color15  #fff8fa
