# Typical conda environment for a reproducible machine learning project
# Use `mamba env create -f environment.yml`
# or `conda env create -f environment.yml` to install the environment
# Created and maintained by garywei944(garywei944@gmail.com)

name: ml
channels:
  - nvidia
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - python>=3.12
  - pip>=25.1
  - cython
  - pocl # for OpenCL
  - nvtop

  # Anaconda
  - _anaconda_depends=2025.06=*openblas*

  # Nvidia cuda drivers
  - nvidia::cuda
  - conda-forge::cudnn
  - conda-forge::nccl

  # pytorch with specific CUDA version
  - conda-forge::pytorch>=2.7.0=*cuda*
  - conda-forge::torchvision=*=*cuda*
  - pytorch::torchtriton
  - conda-forge::flash-attn
  - conda-forge::deepspeed=*=cuda*
  - conda-forge::bitsandbytes=*=cuda*
  - conda-forge::pytorch_geometric
  - conda-forge::pytorch_sparse

  # Huggingface
  - conda-forge::transformers
  - conda-forge::datasets
  - conda-forge::accelerate
  - conda-forge::evaluate
  - conda-forge::peft

  # JAX
  - conda-forge::jaxlib~=0.6.0=*cuda* # flax <- tensorstore <- libprotobuf breaks higher version?
  - conda-forge::jax~=0.6.0
  - conda-forge::flax
  - conda-forge::equinox
  - conda-forge::jaxtyping

  # Tensorflow
  # - conda-forge::tensorflow-gpu=2.17.0
  # - conda-forge::tf-keras=2.17.0 # huggingface import tf_keras
  # - conda-forge::tensorflow-datasets

  # Other ML libraries
  - conda-forge::triton
  - conda-forge::tiktoken

  # Lightning
  - lightning
  - torchmetrics # lighting metrics

  # essential functionality
  - absl-py
  - overrides
  - python-dotenv
  - typing_extensions
  - typeguard
  - beartype

  # argparse
  - typed-argument-parser # for type hinting in argparse
  - jsonargparse # required by lightning[extra]
  - typeshed-client>=2.1.0 # for jsonargparse[signatures] required by lightning[extra]

  # Frameworks
  - opencv
  - pandarallel # for parallel computing panda dataframe
  - einops # for einsum
  - sentencepiece
  - torchinfo

  # utils
  - bayesian-optimization
  - singleton-decorator
  - questionary
  - distro
  - pyprojroot
  - httpie

  # Visualization
  - moviepy # for generating gif

  # Development
  - wandb
  - tensorboardx

  # PyPI common practice
  - setuptools_scm
  - twine
  - blackd
  - bump2version
  - pre-commit # for git hooks

  # Pwntools
  - pwntools

  # If you need to install pip packages, don't do `pip install xxx`
  # Add the package here and run `mamba env update -f environment.yml --prune`
  # for dependency completeness.
  - pip:
      - build
      - datargs
      - sh>=2.2.2
      - morecontext
      - arxiv-latex-cleaner
      - torchopt
      - torch_optimizer
      - separableconv-torch
