# Typical conda environment for a reproducible machine learning project
# Use `mamba env create -f environment.yml`
# or `conda env create -f environment.yml` to install the environment
# Created and maintained by garywei944(garywei944@gmail.com)

name: ml
channels:
  - nvidia
  - pytorch
  - pyg # for pytorch-sparse
  - huggingface
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python>=3.10
  - pip>=24.0
  - cython
  - pocl # for OpenCL
  # - nvtop

  # Anaconda
  - _anaconda_depends=2024.10=*openblas*

  # Nvidia cuda drivers
  - cuda=12.4.1
  - cuda-runtime=12.4.1
  - cuda-toolkit=12.4.1
  - cudnn # https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html
  - pytorch-cuda=12.4

  # pytorch with specific CUDA version
  - pytorch=2.4.1
  - pytorch-mutex=*=cuda # This line sets the mutex for CUDA-enabled PyTorch
  - torchvision
  - torchtriton=3.1.0
  - flash-attn=2.6.3
  # - deepspeed=*=cuda*
  - pyg=2.6.1=*cu*
  - pytorch-sparse=0.6.18=*cu*

  # Huggingface
  - transformers
  - datasets
  - accelerate
  - evaluate
  - tokenizers>=0.13.1 # https://stackoverflow.com/a/74386742
  - peft

  # JAX
  - jaxlib=0.4.31=*cuda* # 0.4.26 doesn't support cuda 11.8
  - jax=0.4.31
  - flax
  - equinox
  - jaxtyping

  # Tensorflow
  - tensorflow-gpu=2.17.0
  - tf-keras=2.17.0 # huggingface import tf_keras
  - tensorflow-datasets

  # Other ML libraries
  - triton=2.0.0

  # Lightning
  - lightning
  # - lightning-bolts~=0.7.0
  - torchmetrics # lighting metrics

  # essential functionality
  - absl-py
  - overrides
  - python-dotenv
  - typing_extensions
  - typeguard
  - beartype

  # argparse
  - omegaconf # for config
  - typed-argument-parser # for type hinting in argparse
  - hydra-core # for config using CLI
  - hydra-submitit-launcher # for submitting jobs to slurm
  - jsonargparse # required by lightning[extra]
  - typeshed-client>=2.1.0 # for jsonargparse[signatures] required by lightning[extra]

  # Frameworks
  - opencv
  - pandarallel # for parallel computing panda dataframe
  - einops # for einsum
  - sentencepiece
  - bitsandbytes
  - torchinfo

  # utils
  - bayesian-optimization
  - singleton-decorator
  - questionary
  - distro

  # Visualization
  - moviepy # for generating gif

  # Development
  - wandb
  - tensorboardx

  # PyPI common practice
  - setuptools_scm
  - twine
  - blackd
  - bump2version
  - pre-commit # for git hooks

  # Pwntools
  - pwntools

  # If you need to install pip packages, don't do `pip install xxx`
  # Add the package here and run `mamba env update -f environment.yml --prune`
  # for dependency completeness.
  - pip:
      - build
      - datargs
      - sh
      - arxiv-latex-cleaner
      # https://github.com/Lightning-AI/pytorch-lightning/blob/master/requirements/pytorch/extra.txt
      # - lightning[pytorch-extra] # the requirements are already included in the file
      # - lightning-gpt
      - torchopt
      - torch_optimizer
      - separableconv-torch
      - cd2root # cd to project root
      # Trial
      - omegaconf-argparse # to use omegaconf with argparse
      - hydra-optuna-sweeper
      - hydra-colorlog
