# Typical conda environment for a reproducible machine learning project
# Use `mamba env create -f environment.yml`
# or `conda env create -f environment.yml` to install the environment
# Created and maintained by garywei944(garywei944@gmail.com)

name: ml-base
channels:
  - nvidia # for CUDA
  - pytorch
  # - pyg # for pytorch-sparse
  # - huggingface
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python>=3.12
  - pip>=24.0
  - cython
  - pocl # for OpenCL

  # System utils
  - psutil
  - nvtop

  # Nvidia cuda drivers
  - nvidia::cuda
  - conda-forge::cudnn
  - conda-forge::nccl

  # essential functionality
  - overrides
  - python-dotenv
  - ruamel.yaml
  - toml
  - absl-py
  - tqdm
  - attrs
  - tabulate
  - typing_extensions
  - rich

  # argparse
  - typed-argument-parser # for type hinting in argparse
  - jsonargparse # required by lightning[extra]
  - typeshed-client>=2.1.0 # for jsonargparse[signatures] required by lightning[extra]

  # Frameworks
  - numpy
  - scipy
  - pandas
  - openpyxl # to open excel files
  - pandarallel # for parallel computing panda dataframe
  - einops
  - sentencepiece
  - bitsandbytes
  - tiktoken

  # pytorch with specific CUDA version
  - conda-forge::pytorch=*=*cuda*
  - conda-forge::torchvision=*=*cuda*
  - pytorch::torchtriton
  - conda-forge::flash-attn
  - conda-forge::deepspeed=*=cuda*
  - conda-forge::bitsandbytes=*=cuda*
  - conda-forge::pytorch_geometric
  - conda-forge::pytorch_sparse

  # scikit-learn
  - scikit-learn
  - scikit-image

  # PyTorch
  - torchinfo

  # Huggingface
  - conda-forge::transformers
  - conda-forge::datasets
  - conda-forge::accelerate
  - conda-forge::evaluate
  - conda-forge::peft

  # JAX
  - conda-forge::jaxlib~=0.6.0=*cuda* # flax <- tensorstore <- libprotobuf breaks higher version?
  - conda-forge::jax=0.6.0
  - conda-forge::flax
  - conda-forge::equinox
  - conda-forge::jaxtyping

  # Lightning
  - conda-forge::lightning
  - conda-forge::torchmetrics # lighting metrics

  # utils
  - bayesian-optimization
  - singleton-decorator
  - questionary
  - distro
  - pyprojroot
  - httpie

  # Visualization
  - matplotlib
  - seaborn
  - moviepy # for generating gif

  # Development
  - jupyter
  - wandb
  - tensorboardx

  # PyPI common practice
  - click
  - setuptools_scm
  - twine # for uploading to pypi
  - blackd # black daemon, for python formatting
  - mypy # for type checking
  - bump2version # for version bump
  - watchdog # filesystem event
  - flake8 # linter
  - tox
  - coverage
  - sphinx # doc
  - pre-commit # for git hooks
  - pytest

  # If you need to install pip packages, don't do `pip install xxx`
  # Add the package here and run `mamba env update -f environment.yml --prune`
  # for dependency completeness.
  - pip:
      - build
      - datargs
      - sh>=2.2.2
      - morecontext
      - arxiv-latex-cleaner
      - torchopt
      - torch_optimizer
      - separableconv-torch
