# Typical conda environment for a reproducible machine learning project
# Use `mamba env create -f environment.yml`
# or `conda env create -f environment.yml` to install the environment
# Created and maintained by garywei944(garywei944@gmail.com)

name: ml-base
channels:
  - pyg # for pytorch-sparse
  - nvidia # for CUDA
  - pytorch
  - huggingface
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python
  - pip
  - cython
  - cudatoolkit
  - pytorch-cuda
  - cudnn # https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html

  # System utils
  - psutil
  - nvtop
  - nvitop

  # essential functionality
  - overrides
  - python-dotenv
  - ruamel.yaml
  - absl-py
  - tqdm
  - attrs
  - tabulate

  # argparse
  - omegaconf # for config
  - typed-argument-parser # for type hinting in argparse
  - hydra-core # for config using CLI

  # Frameworks
  - numpy
  - scipy
  - pandas
  - openpyxl # to open excel files
  - pandarallel # for parallel computing panda dataframe

  # scikit-learn
  - scikit-learn
  - scikit-image

  # PyTorch
  - pytorch
  - torchvision
  - torchinfo
  - pytorch-sparse

  # Huggingface
  - transformers
  - datasets
  - accelerate
  - evaluate
  - tokenizers>=0.13.1 # https://stackoverflow.com/a/74386742
  - peft

  # Lightning
  - lightning
  - lightning-bolts
  - torchmetrics # lighting metrics

  # utils
  - bayesian-optimization
  - singleton-decorator

  # Visualization
  - matplotlib
  - seaborn
  - moviepy # for generating gif

  # Development
  - jupyter
  - wandb
  - tensorboardx

  # PyPI common practice
  - click
  - setuptools_scm
  - twine # for uploading to pypi
  - blackd # black daemon, for python formatting
  - mypy # for type checking
  - bump2version # for version bump
  - watchdog # filesystem event
  - flake8 # linter
  - tox
  - coverage
  - sphinx # doc

  # If you need to install pip packages, don't do `pip install xxx`
  # Add the package here and run `mamba env update -f environment.yml --prune`
  # for dependency completeness.
  - pip:
      - build
      - datargs
      # https://github.com/Lightning-AI/pytorch-lightning/blob/master/requirements/pytorch/extra.txt
      - lightning[pytorch-extra]
      - lightning-gpt
      - sourcery
      - torchopt
      - torch_optimizer
      - separableconv-torch
      - cd2root
      # Trial
      - omegaconf-argparse # to use omegaconf with argparse
