# Typical conda environment for a reproducible machine learning project
# Use `mamba env create -f environment.yml`
# or `conda env create -f environment.yml` to install the environment
# Created and maintained by garywei944(garywei944@gmail.com)

name: jax
channels:
  - nvidia # for CUDA
  - pytorch
  - huggingface
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python>=3.9
  - pip
  - cudatoolkit=11.8
  - cuda-nvcc
  - python-dotenv

  # Anaconda
  - anaconda
  - _anaconda_depends=2022.10

  # Frameworks
  - jax=0.4.8
  - jaxlib=0.4.7=*cuda*
  - opencv
  - pandarallel # for parallel computing panda dataframe

  # utils
  - bayesian-optimization

  # Visualization

  # Development
  - wandb

  # If you need to install pip packages, don't do `pip install xxx`
  # Add the package here and run `mamba env update -f environment.yml --prune`
  # for dependency completeness.
  - pip:
      - singleton-decorator
