# Typical conda environment for a reproducible machine learning project
# Use `mamba env create -f environment.yml`
# or `conda env create -f environment.yml` to install the environment
# Created and maintained by garywei944(garywei944@gmail.com)

name: ml
channels:
  - pyg
  - nvidia # for CUDA
  - pytorch
  - huggingface
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - pip~=23.2.1
  - cython
  - cudatoolkit=11.8
  - pytorch-cuda=11.8
  - cudnn~=8.8.0  # https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html
  - python-dotenv

  # Anaconda
  - anaconda
  - _anaconda_depends~=2023.09

  # Frameworks
  - pandarallel # for parallel computing panda dataframe
  # PyTorch
  - pytorch~=2.1.0
  - torchvision~=0.16.0
  - pytorch-sparse~=0.6.18

  - opencv

  # Huggingface
  - transformers~=4.33.3
  - datasets~=2.14.5
  - accelerate~=0.23.0
  - tokenizers>=0.13.1  # https://stackoverflow.com/a/74386742

  # utils
  - absl-py
  - overrides
  - torchmetrics
  - torchinfo
  - bayesian-optimization

  # Visualization
  - moviepy # for generating gif

  # Development
  - wandb
  - setuptools_scm
  - twine
  - blackd
  - mypy
  - bump2version

  # If you need to install pip packages, don't do `pip install xxx`
  # Add the package here and run `mamba env update -f environment.yml --prune`
  # for dependency completeness.
  - pip:
      - build
      - arxiv-latex-cleaner
      - nvitop # for monitoring GPU usage
      - sourcery
      - singleton-decorator
      - torchopt
      - evaluate
      - pwntools
      - peft
      - separableconv-torch
