# Typical conda environment for a reproducible machine learning project
# Use `mamba env create -f environment.yml`
# or `conda env create -f environment.yml` to install the environment
# Created and maintained by garywei944(garywei944@gmail.com)

name: eva
channels:
  - nvidia # for CUDA
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3
  - pip
  - python-dotenv

  # Anaconda
  - anaconda

  # Frameworks
  - pandarallel # for parallel computing panda dataframe

  # utils
  - pwntools

  # Visualization

  # Development

  # If you need to install pip packages, don't do `pip install xxx`
  # Add the package here and run `mamba env update -f environment.yml --prune`
  # for dependency completeness.
  - pip:
      - singleton-decorator
      - harmony
