# Typical conda environment for a reproducible machine learning project
# Use `mamba env create -f environment.yml`
# or `conda env create -f environment.yml` to install the environment
# Created and maintained by garywei944(garywei944@gmail.com)

name: ml
channels:
  - nvidia # for CUDA
  - pytorch
  - huggingface
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - pip~=23.1.2
  - cython
  - cudatoolkit=11.8
  - pytorch-cuda=11.8
  - cudnn~=8.8.0  # https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html
  - python-dotenv

  # Anaconda
  - anaconda
  - _anaconda_depends=2022.10

  # Frameworks
  - pandarallel # for parallel computing panda dataframe
  # PyTorch
  - pytorch~=2.0.0
  - torchvision
  - pytorch-sparse

  - opencv

  # Huggingface
  - transformers~=4.28.1
  - datasets
  - accelerate
  - tokenizers>=0.13.1  # https://stackoverflow.com/a/74386742

  # utils
  - absl-py
  - torchmetrics
  - torchinfo
  - bayesian-optimization

  # Visualization

  # Development
  - wandb
  - twine

  # If you need to install pip packages, don't do `pip install xxx`
  # Add the package here and run `mamba env update -f environment.yml --prune`
  # for dependency completeness.
  - pip:
      - build
      - singleton-decorator
      - torchopt
      - evaluate
      - pwntools
