[ids]
*

[main]
capslock = overload(control, esc)
esc = capslock

################################################################################
# default using qwerty
################################################################################

pause = toggle(colemak-dh)

[colemak-dh]
# top row
q = q
w = w
e = f
r = p
t = b
y = j
u = l
i = u
o = y
p = semicolon

# home row
a = a
s = r
d = s
f = t
g = g
h = m
j = n
k = e
l = i
semicolon = o

# bottom row (angle mod)
z = z
x = x
c = c
v = d
b = v
n = k
m = h

################################################################################
# default using colemak-dh
################################################################################

# pause = toggle(qwerty)

# # top row
# q = q
# w = w
# e = f
# r = p
# t = b
# y = j
# u = l
# i = u
# o = y
# p = semicolon

# # home row
# a = a
# s = r
# d = s
# f = t
# g = g
# h = m
# j = n
# k = e
# l = i
# semicolon = o

# # bottom row (angle mod)
# z = z
# x = x
# c = c
# v = d
# b = v
# n = k
# m = h

# [qwerty]
# e = e
# r = r
# t = t
# y = y
# u = u
# i = i
# o = o
# p = p
# s = s
# d = d
# f = f
# h = h
# j = j
# k = k
# l = l
# semicolon = semicolon
# n = n
# m = m
# v = v
# b = b
