# plugin {
#     split-monitor-workspaces {
#         count = 9
#         keep_focused = 0
#         enable_persistent_workspaces = 1
#         enable_wrapping = 1
#         # Controls which monitor gets 1-9, 10-18, 19-27.
#         # Order: DP-1 first → gets 1-9, DP-2 → 10-18, DP-3 → 19-27
#         monitor_priority = DP-1, DP-2, DP-3
#     }
# }

plugin {
    hyprsplit {
        num_workspaces = 9
        persistent_workspaces = true
        monitor_priority = DP-1, DP-2, DP-3
    }
}

# DP-1 (ID 0) — 1..9
workspace = 1, defaultName:1-1 | Code
workspace = 2, defaultName:1-2 | Web
workspace = 3, defaultName:1-3 | Folder
workspace = 4, defaultName:1-4 | Doc
workspace = 5, defaultName:1-5 | App
workspace = 6, defaultName:1-6 | Code
workspace = 7, defaultName:1-7 | Web
workspace = 8, defaultName:1-8 | Terminal
workspace = 9, defaultName:1-9 | Reserve

# DP-2 (ID 1) — 10..18
workspace = 10, defaultName:2-1 | Code
workspace = 11, defaultName:2-2 | Web
workspace = 12, defaultName:2-3 | Folder
workspace = 13, defaultName:2-4 | Doc
workspace = 14, defaultName:2-5 | App
workspace = 15, defaultName:2-6 | Code
workspace = 16, defaultName:2-7 | Web
workspace = 17, defaultName:2-8 | Terminal
workspace = 18, defaultName:2-9 | Reserve

# DP-3 (ID 2) — 19..27
workspace = 19, defaultName:3-1 | Web
workspace = 20, defaultName:3-2 | Chat
workspace = 21, defaultName:3-3 | Git
workspace = 22, defaultName:3-4 | Doc
workspace = 23, defaultName:3-5 | App
workspace = 24, defaultName:3-6 | Code
workspace = 25, defaultName:3-7 | Music
workspace = 26, defaultName:3-8 | Terminal
workspace = 27, defaultName:3-9 | Reserve

plugin {
  easymotion {
    #font size of the text
    textsize=48

    #color of the text, takes standard hyprland color format
    textcolor=rgba(ffffffff)

    #background color of the label box. alpha is respected
    bgcolor=rgba(000000ff)

    #enable blur. The bgcolor alpha must be at least semi-transparent.
    blur=0

    #Set blur alpha value. Blur must be enabled (float value)
    blurA=1.0

    #Set xray. Blur must be enabled
    xray=0

    #font to use for the label. This is passed directly to the pango font description
    textfont=Sans

    #padding around the text (inside the label box) size in pixels, adjusted for
    #monitor scaling. This is the same format as hyprland's gapsin/gapsout workspace layout rule
    #example: textpadding=2 5 5 2 (spaces not commas)
    textpadding=0

    #size of the border around the label box. A border size of zero disables border rendering.
    bordersize=0

    #color of the border. takes the same format as hyprland's border (so it can be a gradient)
    bordercolor=rgba(ffffffff)

    #rounded corners? Same as hyprland's 'decoration:rounding' config
    rounding=0

    #what to do if a window is fullscreen
    #none: nothing. (easymotion label won't be displayed on that window)
    #toggle: take the window out of fullscreen entirely.
    #maximize: convert the window to maximized.
    #windows are restored to fullscreen after easymotion is exited/selected
    fullscreen_action=none

    #which keys to use for selecting windows
    motionkeys=abcdefghijklmnopqrstuvwxyz1234567890
    #which keys to use for labeling windows
    motionlabels=ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890

    #if a monitor has a focused special workspace, only put easymotion labels on the windows in the special workspace
    only_special = true
  }
}
