[colors.primary]
background = '#0f1511'
foreground = '#dfe4dd'

[colors.selection]
text = '#dfe4dd'
background = '#0d5130'

[colors.cursor]
text = '#0f1511'
cursor = '#94d5a9'

[colors.normal]
black   = '#0f1511'
red     = '#f4936e'
green   = '#6ad56c'
yellow  = '#fff072'
blue    = '#80ca98'
magenta = '#2b623d'
cyan    = '#94d5a9'
white   = '#d2dfd6'

[colors.bright]
black   = '#808a83'
red     = '#ffba9f'
green   = '#a5ffa7'
yellow  = '#fff6a5'
blue    = '#adeac1'
magenta = '#c8ffda'
cyan    = '#dbffe7'
white   = '#f8fffa'
