[colors.primary]
background = '#19120d'
foreground = '#f0dfd6'

[colors.selection]
text = '#f0dfd6'
background = '#6e390d'

[colors.cursor]
text = '#19120d'
cursor = '#ffb785'

[colors.normal]
black   = '#19120d'
red     = '#ff7972'
green   = '#96ff7f'
yellow  = '#ffe672'
blue    = '#f2a067'
magenta = '#76380e'
cyan    = '#ffb785'
white   = '#fff5ef'

[colors.bright]
black   = '#a59e99'
red     = '#ffa49f'
green   = '#b5ffa5'
yellow  = '#ffefa5'
blue    = '#ffc197'
magenta = '#ffcca9'
cyan    = '#ffdec8'
white   = '#fffbf8'
