-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
    general = {
        col = {
            active_border = "rgb(ffb785)",
            inactive_border = "rgb(9f8d83)",
        },
    },
    group = {
        col = {
            border_active = "rgb(ffb785)",
            border_inactive = "rgb(9f8d83)",
            border_locked_active = "rgb(ffb4ab)",
            border_locked_inactive = "rgb(9f8d83)",
        },
        groupbar = {
            col = {
                active = "rgb(ffb785)",
                inactive = "rgb(9f8d83)",
                locked_active = "rgb(ffb4ab)",
                locked_inactive = "rgb(9f8d83)",
            },
        },
    },
})
