.PHONY: install

install:
	git clone --depth 1 https://github.com/lcpz/awesome-freedesktop.git ~/.config/awesome/freedesktop
	git clone --depth 1 https://github.com/lcpz/lain.git ~/.config/awesome/lain
